# appspec.yml

  version: 0.0
  os: linux
  files:
    - source: /
      destination: /home/ec2-user/env/WhaleDone-Server/ # 프로젝트 이름
      overwrite: yes

  permissions:
    - object: /
      pattern: "**"
      owner: ec2-user
      group: ec2-user

  hooks:
    BeforeInstall:
      - location: scripts/beforeInstall.bash
    ApplicationStart:
      - location: scripts/deploy.sh
        timeout: 180
        runas: ec2-user
      - location: scripts/health_check.sh
        timeout: 180
        runas: ec2-user
      - location: scripts/switch.sh
        timeout: 180
        runas: ec2-user
