spring:
  profiles:
    default: local

---
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(47+QKgqH4tEQEv+ksFCBTa9bLOE8m7Vych8ioXlYvHA=)
    password: ENC(0FYTVKvrToK8gmcXEfBXhMga4ZLb8CaI)
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    operations-sorter: method
  paths-to-match: /api/v1/**

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_WHALEDONE_PASSWORD}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
      instanceProfile: true
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
sms:
  serviceId: ENC(MPBlTyioehVlME4NNTstDO1uthn12J59yrIWqFHcJYZPwjekgPmEa74Srlaj8Z5z)
  accessKey: ENC(m/SYmOG/GEfDYeRelvUE8OkN2tDa+tTg4pnezh9Q6Us=)
  secretKey: ENC(rtO5xCkUQ+c9FybgG7ePYgFM+XsUU1QiEfXUjdrSDSXZ0e8c/wM1D3Fk79KyT+weGHAaM3yKmL0=)
  from: ENC(Nhuw02FTD8upol2UopaXBaBuxOxnf7QY)

---
spring:
  profiles:
    active: local

  datasource:
    url: ENC(Kr8E0OlXtZN9I9S9HOub0IL7TuE3haexd5LmKaEzI8GVCW/tm1CEFYzwd/RQK3Tra6t/tfbthvhW6JHDZFqQrXrUT4Z3wbYN5LPqUVHxTDno0JVnOTnC1v9SBuWnfr/QF9olDZnZAYWhIJvtz7441Om2eqpj6XYQV/dLQSCTiE4sVb4wyP8gwRWu+gvRWbXn)
    username: ENC(OhuwwEwv/yiitEjNJEaypg==)
    password: ENC(13pgTJX3wcMivrY26S7+nTS+T0Mnto/u)
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  profiles:
    active: dev

  datasource:
    url: ENC(Kr8E0OlXtZN9I9S9HOub0IL7TuE3haexd5LmKaEzI8GVCW/tm1CEFYzwd/RQK3Tra6t/tfbthvhW6JHDZFqQrXrUT4Z3wbYN5LPqUVHxTDno0JVnOTnC1v9SBuWnfr/QF9olDZnZAYWhIJvtz7441Om2eqpj6XYQV/dLQSCTiE4sVb4wyP8gwRWu+gvRWbXn)
    username: ENC(OhuwwEwv/yiitEjNJEaypg==)
    password: ENC(13pgTJX3wcMivrY26S7+nTS+T0Mnto/u)
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  profiles:
    active: prod

  datasource:
    url: ENC(EK4xmbAxTcOPjRemM015hg0GGSpXLhZ0fJM1MUK3qiJmMeVc3XkmI6uGS20fzvoME2zx14VPT/pdGDhtZOYar+Zik6kNJrNTlA7c7SFLS9OKtxw1+kG7Uv36EOnu/XUShIEsO1SRsMsCuAVYSyjfs5IFtiJ9mzZgoldiB9P7OCRiftSsFrb5FNF8P9FeZWj4+/01dOSBgOo=)
    username: ENC(qLsMCntprioDPU148VjpsQ==)
    password: ENC(EIuivMF08oFs7Ag5eh3unn38ZNc+XCYR)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
